const alphabetData = [
    // HIRAGANA
    {
        char: "あ",
        romaji: "a",
        row: "A",
        type: "hiragana",
        example: "Ai (Tình yêu)",
    },
    {
        char: "い",
        romaji: "i",
        row: "A",
        type: "hiragana",
        example: "Ie (Ngôi nhà)",
    },
    {
        char: "う",
        romaji: "u",
        row: "A",
        type: "hiragana",
        example: "Ushi (Con bò)",
    },
    {
        char: "え",
        romaji: "e",
        row: "A",
        type: "hiragana",
        example: "Eki (Nhà ga)",
    },
    {
        char: "お",
        romaji: "o",
        row: "A",
        type: "hiragana",
        example: "Onigiri (Cơm nắm)",
    },
    {
        char: "か",
        romaji: "ka",
        row: "K",
        type: "hiragana",
        example: "Kasa (Cái ô)",
    },
    {
        char: "き",
        romaji: "ki",
        row: "K",
        type: "hiragana",
        example: "Ki (Cái cây)",
    },
    {
        char: "く",
        romaji: "ku",
        row: "K",
        type: "hiragana",
        example: "Kuma (Con gấu)",
    },
    {
        char: "け",
        romaji: "ke",
        row: "K",
        type: "hiragana",
        example: "Keshigomu (Cục tẩy)",
    },
    {
        char: "こ",
        romaji: "ko",
        row: "K",
        type: "hiragana",
        example: "Koko (Ở đây)",
    },
    {
        char: "さ",
        romaji: "sa",
        row: "S",
        type: "hiragana",
        example: "Sakura (Hoa anh đào)",
    },
    {
        char: "し",
        romaji: "shi",
        row: "S",
        type: "hiragana",
        example: "Shio (Muối)",
    },
    {
        char: "す",
        romaji: "su",
        row: "S",
        type: "hiragana",
        example: "Sushi (Món Sushi)",
    },
    {
        char: "せ",
        romaji: "se",
        row: "S",
        type: "hiragana",
        example: "Sekai (Thế giới)",
    },
    {
        char: "そ",
        romaji: "so",
        row: "S",
        type: "hiragana",
        example: "Sora (Bầu trời)",
    },
    {
        char: "た",
        romaji: "ta",
        row: "T",
        type: "hiragana",
        example: "Tako (Con bạch tuộc)",
    },
    {
        char: "ち",
        romaji: "chi",
        row: "T",
        type: "hiragana",
        example: "Chizu (Bản đồ)",
    },
    {
        char: "つ",
        romaji: "tsu",
        row: "T",
        type: "hiragana",
        example: "Tsuki (Mặt trăng)",
    },
    {
        char: "て",
        romaji: "te",
        row: "T",
        type: "hiragana",
        example: "Te (Bàn tay)",
    },
    {
        char: "と",
        romaji: "to",
        row: "T",
        type: "hiragana",
        example: "Tokei (Đồng hồ)",
    },
    {
        char: "な",
        romaji: "na",
        row: "N",
        type: "hiragana",
        example: "Neko (Con mèo)",
    },
    {
        char: "に",
        romaji: "ni",
        row: "N",
        type: "hiragana",
        example: "Niku (Thịt)",
    },
    {
        char: "ぬ",
        romaji: "nu",
        row: "N",
        type: "hiragana",
        example: "Inu (Con chó)",
    },
    {
        char: "ね",
        romaji: "ne",
        row: "N",
        type: "hiragana",
        example: "Nezumi (Con chuột)",
    },
    {
        char: "の",
        romaji: "no",
        row: "N",
        type: "hiragana",
        example: "Nori (Rong biển)",
    },
    {
        char: "は",
        romaji: "ha",
        row: "H",
        type: "hiragana",
        example: "Hana (Hoa)",
    },
    {
        char: "ひ",
        romaji: "hi",
        row: "H",
        type: "hiragana",
        example: "Hito (Người)",
    },
    {
        char: "ふ",
        romaji: "fu",
        row: "H",
        type: "hiragana",
        example: "Fune (Tàu thuyền)",
    },
    {
        char: "へ",
        romaji: "he",
        row: "H",
        type: "hiragana",
        example: "Hebi (Con rắn)",
    },
    {
        char: "ほ",
        romaji: "ho",
        row: "H",
        type: "hiragana",
        example: "Hoshi (Ngôi sao)",
    },
    {
        char: "ま",
        romaji: "ma",
        row: "M",
        type: "hiragana",
        example: "Mado (Cửa sổ)",
    },
    {
        char: "み",
        romaji: "mi",
        row: "M",
        type: "hiragana",
        example: "Mizu (Nước)",
    },
    {
        char: "む",
        romaji: "mu",
        row: "M",
        type: "hiragana",
        example: "Mushi (Côn trùng)",
    },
    {
        char: "め",
        romaji: "me",
        row: "M",
        type: "hiragana",
        example: "Me (Mắt)",
    },
    {
        char: "も",
        romaji: "mo",
        row: "M",
        type: "hiragana",
        example: "Momo (Quả đào)",
    },
    {
        char: "や",
        romaji: "ya",
        row: "Y",
        type: "hiragana",
        example: "Yama (Núi)",
    },
    {
        char: "ゆ",
        romaji: "yu",
        row: "Y",
        type: "hiragana",
        example: "Yuki (Tuyết)",
    },
    {
        char: "よ",
        romaji: "yo",
        row: "Y",
        type: "hiragana",
        example: "Yoru (Đêm)",
    },
    {
        char: "ら",
        romaji: "ra",
        row: "R",
        type: "hiragana",
        example: "Raion (Sư tử)",
    },
    {
        char: "り",
        romaji: "ri",
        row: "R",
        type: "hiragana",
        example: "Ringo (Quả táo)",
    },
    {
        char: "る",
        romaji: "ru",
        row: "R",
        type: "hiragana",
        example: "Rusu (Vắng nhà)",
    },
    {
        char: "れ",
        romaji: "re",
        row: "R",
        type: "hiragana",
        example: "Rekishi (Lịch sử)",
    },
    {
        char: "ろ",
        romaji: "ro",
        row: "R",
        type: "hiragana",
        example: "Roku (Số 6)",
    },
    {
        char: "わ",
        romaji: "wa",
        row: "W",
        type: "hiragana",
        example: "Wani (Cá sấu)",
    },
    { char: "を", romaji: "wo", row: "W", type: "hiragana", example: "Trợ từ" },
    {
        char: "ん",
        romaji: "n",
        row: "N",
        type: "hiragana",
        example: "Hon (Sách)",
    },

    // KATAKANA
    {
        char: "ア",
        romaji: "a",
        row: "A",
        type: "katakana",
        example: "Aisu (Ice cream)",
    },
    {
        char: "イ",
        romaji: "i",
        row: "A",
        type: "katakana",
        example: "Inku (Ink)",
    },
    {
        char: "ウ",
        romaji: "u",
        row: "A",
        type: "katakana",
        example: "Uirusu (Virus)",
    },
    {
        char: "エ",
        romaji: "e",
        row: "A",
        type: "katakana",
        example: "Erebeetaa (Elevator)",
    },
    {
        char: "オ",
        romaji: "o",
        row: "A",
        type: "katakana",
        example: "Orenji (Orange)",
    },
    {
        char: "カ",
        romaji: "ka",
        row: "K",
        type: "katakana",
        example: "Kamera (Camera)",
    },
    {
        char: "キ",
        romaji: "ki",
        row: "K",
        type: "katakana",
        example: "Kii (Key)",
    },
    {
        char: "ク",
        romaji: "ku",
        row: "K",
        type: "katakana",
        example: "Kurasu (Class)",
    },
    {
        char: "ケ",
        romaji: "ke",
        row: "K",
        type: "katakana",
        example: "Keeki (Cake)",
    },
    {
        char: "コ",
        romaji: "ko",
        row: "K",
        type: "katakana",
        example: "Koohii (Coffee)",
    },
    {
        char: "サ",
        romaji: "sa",
        row: "S",
        type: "katakana",
        example: "Sadaa (Salad)",
    },
    {
        char: "シ",
        romaji: "shi",
        row: "S",
        type: "katakana",
        example: "Shatsu (Shirt)",
    },
    {
        char: "ス",
        romaji: "su",
        row: "S",
        type: "katakana",
        example: "Suupu (Soup)",
    },
    {
        char: "セ",
        romaji: "se",
        row: "S",
        type: "katakana",
        example: "Setaa (Sweater)",
    },
    {
        char: "ソ",
        romaji: "so",
        row: "S",
        type: "katakana",
        example: "Soosu (Sauce)",
    },
    {
        char: "タ",
        romaji: "ta",
        row: "T",
        type: "katakana",
        example: "Takushii (Taxi)",
    },
    {
        char: "チ",
        romaji: "chi",
        row: "T",
        type: "katakana",
        example: "Chiizu (Cheese)",
    },
    {
        char: "ツ",
        romaji: "tsu",
        row: "T",
        type: "katakana",
        example: "Tsuaa (Tour)",
    },
    {
        char: "テ",
        romaji: "te",
        row: "T",
        type: "katakana",
        example: "Tenisu (Tennis)",
    },
    {
        char: "ト",
        romaji: "to",
        row: "T",
        type: "katakana",
        example: "Tomato (Tomato)",
    },
    {
        char: "ナ",
        romaji: "na",
        row: "N",
        type: "katakana",
        example: "Naifu (Knife)",
    },
    {
        char: "ニ",
        romaji: "ni",
        row: "N",
        type: "katakana",
        example: "Nyusu (News)",
    },
    {
        char: "ヌ",
        romaji: "nu",
        row: "N",
        type: "katakana",
        example: "Nudoru (Noodle)",
    },
    {
        char: "ネ",
        romaji: "ne",
        row: "N",
        type: "katakana",
        example: "Nekutai (Necktie)",
    },
    {
        char: "ノ",
        romaji: "no",
        row: "N",
        type: "katakana",
        example: "Nooto (Note)",
    },
    {
        char: "ハ",
        point: "ha",
        row: "H",
        type: "katakana",
        example: "Hamu (Ham)",
    },
    {
        char: "ヒ",
        romaji: "hi",
        row: "H",
        type: "katakana",
        example: "Hiitaa (Heater)",
    },
    {
        char: "フ",
        romaji: "fu",
        row: "H",
        type: "katakana",
        example: "Fooku (Fork)",
    },
    {
        char: "ヘ",
        romaji: "he",
        row: "H",
        type: "katakana",
        example: "Herumetto (Helmet)",
    },
    {
        char: "ホ",
        romaji: "ho",
        row: "H",
        type: "katakana",
        example: "Hoteru (Hotel)",
    },
    {
        char: "マ",
        romaji: "ma",
        row: "M",
        type: "katakana",
        example: "Maiku (Mic)",
    },
    {
        char: "ミ",
        romaji: "mi",
        row: "M",
        type: "katakana",
        example: "Miruku (Milk)",
    },
    {
        char: "ム",
        romaji: "mu",
        row: "M",
        type: "katakana",
        example: "Mubi (Movie)",
    },
    {
        char: "メ",
        romaji: "me",
        row: "M",
        type: "katakana",
        example: "Meron (Melon)",
    },
    {
        char: "モ",
        romaji: "mo",
        row: "M",
        type: "katakana",
        example: "Monitaa (Monitor)",
    },
    {
        char: "ヤ",
        romaji: "ya",
        row: "Y",
        type: "katakana",
        example: "Yotto (Yacht)",
    },
    {
        char: "ユ",
        romaji: "yu",
        row: "Y",
        type: "katakana",
        example: "Yunifoomu (Uniform)",
    },
    {
        char: "ヨ",
        romaji: "yo",
        row: "Y",
        type: "katakana",
        example: "Yooguruto (Yogurt)",
    },
    {
        char: "ラ",
        romaji: "ra",
        row: "R",
        type: "katakana",
        example: "Rajio (Radio)",
    },
    {
        char: "リ",
        romaji: "ri",
        row: "R",
        type: "katakana",
        example: "Rimoto (Remote)",
    },
    {
        char: "ル",
        romaji: "ru",
        row: "R",
        type: "katakana",
        example: "Rupu (Loop)",
    },
    {
        char: "レ",
        romaji: "re",
        row: "R",
        type: "katakana",
        example: "Resutoran (Restaurant)",
    },
    {
        char: "ロ",
        romaji: "ro",
        row: "R",
        type: "katakana",
        example: "Robotto (Robot)",
    },
    {
        char: "ワ",
        romaji: "wa",
        row: "W",
        type: "katakana",
        example: "Wain (Wine)",
    },
    { char: "ヲ", romaji: "wo", row: "W", type: "katakana", example: "Trợ từ" },
    {
        char: "ン",
        romaji: "n",
        row: "N",
        type: "katakana",
        example: "Pan (Bánh mì)",
    },
];
